### ISSUE TITLE
All rules are off

### ISSUE THREAD

**Issue by TheElegantCoding** [oxc-project/eslint-plugin-oxlint#200]
Maybe I'm configuring this plugin wrong, i have a configuration similar to [eslint-antfu](https://github.com/antfu/eslint-config) my configuration [here](https://github.com/TheElegantCoding/eslint-config-elegant-coding)

as the doc says I installed oxc in vscode and added this in my config

```js
import oxlint from 'eslint-plugin-oxlint';
export default [
  ...// other plugins
  oxlint.configs['flat/recommended'], // oxlint should be the last one
];
```

My eslint config viewer says i have all the rules off by default 

![image](https://github.com/user-attachments/assets/43c58cb1-7413-4863-aa89-a9b98ad7bea5)

Do you know if I need to configure every rule manual ? this is not specified in the doc

**Comment by Sysix** [comment]
This plugin only disables rules which are currently supported by [oxlint](https://www.npmjs.com/package/oxlint).
Because you used `flat/all` it disables [every supported plugin](https://oxc.rs/docs/guide/usage/linter/plugins.html#supported-plugins).

It does not enable rules! You can pick plugins you want to disables like:
```
import oxlint from 'eslint-plugin-oxlint';
export default [
  ...// other plugins
  oxlint.configs['flat/eslint'],
  oxlint.configs['flat/import'],
  oxlint.configs['flat/unicorn'],
  oxlint.configs['flat/node'],
];
```

**Comment by TheElegantCoding** [comment]
I get it, so this is the default behavior is to disable the rules for eslint and oxc make the work
